config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :users, only: [:new, :create, :show] do
    resources :stories
  end
  
  get "/all_stories", to: 'stories#all_stories', as: 'all_stories'
  get '/all_stories/show/:id', to: 'stories#all_stories_show', as: 'all_stories_show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates :rating, inclusion: {in: 0..5}
  
  belongs_to :user
  belongs_to :story
end

app/models/story.rb
class Story < ApplicationRecord
  # has_many :ratings, :dependent => :destroy
  # has_many :users, through: :ratings

  has_many :user_stories, :dependent => :destroy
  has_many :users, through: :user_stories
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true

  # has_many :ratings, dependent: :destroy
  # has_many :stories, through: :ratings

  has_many :user_stories, dependent: :destroy
  has_many :stories, through: :user_stories
end

app/models/user_story.rb
class UserStory < ApplicationRecord
  belongs_to :user
  belongs_to :story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      session[:logged_in?] = true
      redirect_to user_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @stories = @user.stories
  end

  def new
    @user = User.find(params[:user_id])
    @story = Story.new
  end

  def create
    @user = User.find(params[:user_id])
    @story = Story.create(story_params)
    @user_story = UserStory.create(user_id: @user.id, story_id: @story.id)
    redirect_to user_story_path(@user, @story)
  end

  def show
    @user = User.find(params[:user_id])
    @story = Story.find(params[:id])
  end


  def edit
    @user = User.find(params[:user_id])
    @story = Story.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @story = Story.find(params[:id])
    @story.update(story_params)
    redirect_to user_story_path(@user, @story)
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  def all_stories
    @stories = Story.all
  end

  def all_stories_show
    @story = Story.find(params[:id])
  end

  private

  def story_params
    params.require(:story).permit(:name_1, :verb_1, :adj_1, :adv_1, :fam, :name_2, :number, :verb_2, :noun_1, :mil_rank, :adj_2, :adj_3, :adj_4, :noun_2, :award, :adj_5, :name_3, :verb_3, :noun_3, :verb_4, :adj_6, :verb_5, :verb_6, :emotion, :name_4, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      session[:logged_in?] = true
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :picture)
  end

  def require_login
    unless session[:logged_in?]
      flash[:error] = "You must be logged in to view this content"
      redirect_to login_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/madlibs_helper.rb
module MadlibsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthenticationAuthorizationExample</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> -->
  <style>
    h3 {
      color: black;
    }
    h1 {
      color: black;
    }
    p {
      color: black;
    }
  </style>
</head>

<body>
  <div class ="container">
    <% if current_user %>
      <p> Logged in as <%= current_user.username %>
      <%= link_to "User Page", user_path(current_user)%>
      <%= button_to "Logout", logout_path, method: :delete %></p>
    <% end %>
    <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash_#{type}" %>
    <% end %>
  </div>
  <div class ="container">
    <div class="page-header">
      <h3><small></small></h3>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/stories/all_stories.html.erb
<h1>Story Index</h1>

<% @stories.each do |story| %>
  <li><%= link_to "Eulogy", all_stories_show_path(story) %> by: <%= story.name_1 %></br> created on: <%= story.created_at %></li>
<% end %>
<br/>

<%= link_to "Back to Welcome Page: Become a User", root_path %>

app/views/stories/all_stories_show.html.erb
<h1> "Eulogy"</h1>
<h3> This magnificent drivel brought to you by: You'll never know! </h3>

<p>   If you are <%= @story.verb_1 %> this, it means I am <%= @story.adj_1 %>.  I am sure you are all <%= @story.adv_1 %> grieved.  Especially my <%= @story.fam %> <%= @story.name_2 %>, and our <%= @story.number %> children.  In my life, I <%= @story.verb_2 %> for many popular <%= @story.noun_1 %> shows, including '<%= @story.mil_rank %> Bilko' and 'Get <%= @story.adj_2 %>'.  I led a <%= @story.adj_3 %> life, filled with <%= @story.adj_4 %> <%= @story.noun_2 %> and even better memories.  I'll never forget the day I won my <%= @story.award %> award, and showed it to my lover.  They remarked, "It's so much <%= @story.adj_5 %> than I thought!", to which I replied, "That's what <%= @story.name_3 %> said."  We laughed and <%= @story.verb_3 %>.  I hope to be remembered as a <%= @story.noun_3 %>, who loved to make people <%= @story.verb_4 %>, but more importantly, as a(n) <%= @story.adj_6 %> individual.  Thank you all for <%= @story.verb_5 %>, I promise not to <%= @story.verb_6 %> you while you sleep.<br/>
<%= @story.emotion %> forever,  <%= @story.name_4 %></p><br/>


<%= image_tag(@story.picture) %><br/>
<%= link_to "Back", all_stories_path %><br/>

app/views/stories/edit.html.erb
<h1>Edit your Eulogy: Add a Picture</h1>

<%= form_for [@user, @story] do |f| %>
  <%= f.label :picture, "Place Image URL here:" %><br/>
  <%= f.text_field :picture %><br/>
  <%= f.submit %>
<% end %>

app/views/stories/index.html.erb
<h1> My Eulogy Index </h1>

<% @stories.each do |story| %>
  <li><%= link_to "Eulogy", user_story_path(@user, story) %> by: <%= story.name_1 %></br> created on: <%= story.created_at %></li>
  <%= link_to "DELETE this Awful Insult to Literature", user_story_path(@user, story), method: :delete %><br/>
<% end %>

app/views/stories/new.html.erb
<h1>Create a new Madlib</h1>

<%= form_for [@user, @story] do |f| %>
  <%= f.label :name_1, "Your name" %><br/>
  <%= f.text_field :name_1 %><br/>
  <%= f.label :name_2, "any name:" %><br/>
  <%= f.text_field :name_2 %><br/>
  <%= f.label :name_3, "any name:" %><br/>
  <%= f.text_field :name_3 %><br/>
  <%= f.label :adv_1, "adverb:" %><br/>
  <%= f.text_field :adv_1 %><br/>
  <%= f.label :award, "an award:" %><br/>
  <%= f.text_field :award %><br/>
  <%= f.label :verb_1, "verb + ing:"%><br/>
  <%= f.text_field :verb_1 %><br/>
  <%= f.label :verb_2, "verb (past tense):" %><br/>
  <%= f.text_field :verb_2 %><br/>
  <%= f.label :verb_3, "verb (past tense):" %><br/>
  <%= f.text_field :verb_3 %><br/>
  <%= f.label :verb_4, "verb (present tense):" %><br/>
  <%= f.text_field :verb_4 %><br/>
  <%= f.label :verb_5, "verb + ing:" %><br/>
  <%= f.text_field :verb_5 %><br/>
  <%= f.label :verb_6, "verb (present tense):" %><br/>
  <%= f.text_field :verb_6 %><br/>
  <%= f.label :fam, "family member relationship (ex: father, aunt):" %><br/>
  <%= f.text_field :fam %><br/>
  <%= f.label :number, "a number (0-1000):" %><br/>
  <%= f.text_field :number %><br/>
  <%= f.label :adj_1, "state of being (alive/dead/something else):" %><br/>
  <%= f.text_field :adj_1 %><br/>
  <%= f.label :adj_2, "adjective:" %><br/>
  <%= f.text_field :adj_2 %><br/>
  <%= f.label :adj_3, "adjective:" %><br/>
  <%= f.text_field :adj_3 %><br/>
  <%= f.label :adj_4, "adjective:" %><br/>
  <%= f.text_field :adj_4 %><br/>
  <%= f.label :adj_6, "adjective:" %><br/>
  <%= f.text_field :adj_6 %><br/>
  <%= f.label :adj_5, "adjective + er:" %><br/>
  <%= f.text_field :adj_5 %><br/>
  <%= f.label :mil_rank, "military rank:" %><br/>
  <%= f.text_field :mil_rank %><br/>
  <%= f.label :noun_1, "noun:" %><br/>
  <%= f.text_field :noun_1 %><br/>
  <%= f.label :noun_3, "noun:" %><br/>
  <%= f.text_field :noun_3 %><br/>
  <%= f.label :noun_2, "plural noun:" %><br/>
  <%= f.text_field :noun_2 %><br/>
  <%= f.label :emotion, "a feeling/an emotion (ex: sad, angry):" %><br/>
  <%= f.text_field :emotion %><br/>
  <%= f.label :name_4, "your own name again, but make it sound pretentious/pompous:" %><br/>
  <%= f.text_field :name_4 %><br/>
  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<h1> "Eulogy"</h1>
<h3> This magnificent drivel brought to you by: <%= @story.name_1 %> </h3>
<%= link_to "EDIT this Abomination to have your image", edit_user_story_path(@user, @story) %><br/>

<p>   If you are <%= @story.verb_1 %> this, it means I am <%= @story.adj_1 %>.  I am sure you are all <%= @story.adv_1 %> grieved.  Especially my <%= @story.fam %> <%= @story.name_2 %>, and our <%= @story.number %> children.  In my life, I <%= @story.verb_2 %> for many popular <%= @story.noun_1 %> shows, including '<%= @story.mil_rank %> Bilko' and 'Get <%= @story.adj_2 %>'.  I led a <%= @story.adj_3 %> life, filled with <%= @story.adj_4 %> <%= @story.noun_2 %> and even better memories.  I'll never forget the day I won my <%= @story.award %> award, and showed it to my lover.  They remarked, "It's so much <%= @story.adj_5 %> than I thought!", to which I replied, "That's what <%= @story.name_3 %> said."  We laughed and <%= @story.verb_3 %>.  I hope to be remembered as a <%= @story.noun_3 %>, who loved to make people <%= @story.verb_4 %>, but more importantly, as a(n) <%= @story.adj_6 %> individual.  Thank you all for <%= @story.verb_5 %>, I promise not to <%= @story.verb_6 %> you while you sleep.<br/>
<%= @story.emotion %> forever,  <%= @story.name_4 %></p><br/>


<%= image_tag(@story.picture) %><br/>
<%= link_to "Back", user_stories_path %><br/>

app/views/user/show.html.erb
<h1><%= @user.username %>'s Page</h1>

<%= image_tag(@user.picture) %>

<p> User's stories here - link to each stories show page </p> 

<%= link_to "Logout", logout_path, method: :delete %>

app/views/users/new.html.erb
<h1> Create a New Account </h1>

<%= form_for(@user) do |f| %>
  <%= f.label :username, "Username:" %><br/>
  <%= f.text_field :username %><br/>

  <%= f.label :password, "Password:" %><br/>
  <%= f.password_field :password %><br/>

  <%= f.label :picture, "Add URL for a picture here (keep it smallish):" %><br/>
  <%= f.text_field :picture %><br/><br/>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Page</h1>

<%= image_tag(@user.picture) %><br/>

<%= link_to "My Stories", user_stories_path(@user) %><br/>
<%= link_to "Create a New Story", new_user_story_path(@user) %><br/>
<%= link_to "All Stories, From Everyone, not JUST you...selfish bastard", all_stories_path %><br/>

app/views/welcome/index.html.erb
<h1> Welcome to Fun Times</h1>

<%= image_tag('http://i.huffpost.com/gen/2130862/images/o-VOICE-SOUNDS-WEIRD-facebook.jpg', size: "720x320") %><br/>

<%= link_to "Create New User", new_user_path %><br/>
<%= link_to "Already a user, Click Here!", login_path %><br/>
<%= link_to "Story Index for visitors", all_stories_path %><br/>